apiVersion: v1
kind: Secret
metadata:
  name: journey-app-secret
type: Opaque
stringData:
  DB_HOST: {{ .Values.secrets.dbHost | quote }}
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_NAME: {{ .Values.secrets.dbName | quote }}
  POSTGRES_USER: {{ .Values.secrets.dbUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.dbName | quote }}